"""Fix user password column

Revision ID: c25739c5a227
Revises: eb8c27086ed5
Create Date: 2025-09-19 02:43:14.580809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c25739c5a227'
down_revision = 'eb8c27086ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('supplier')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
