"""Fix user password column name

Revision ID: ef03b8856103
Revises: c25739c5a227
Create Date: 2025-09-19 03:02:27.104747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef03b8856103'
down_revision = 'c25739c5a227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=200), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
